=head1 Programmation web - Projet PHP

JeNeSaisPasCuisiner.com

=head2 Lien utiles

Lisez bien ce qui suit (#RTFM)

=head3 Howto git

=over 4

=item Tuto @SDZ

L<http://www.siteduzero.com/tutoriel-3-254198-gerez-vos-codes-source-avec-git.html>

=item SmartGIT (GUI)

L<http://www.syntevo.com/smartgit/index.html>

=back

=head2 Contact

mailme !

=cut
