=head1 Programmation web - Projet PHP

JeNeSaisPasCuisiner.com

=head2 TODO

=over

=item Separer le code PHP de l'HTML

=item Ameloirer la recherche

=item Afficher des liens vers les recettes trouvees

=item Refuser l'acces (rediriger vers l'accueil) a update.php etc. si l'utilisateur n'est pas logge

=item Permettre aux utilisateurs non-enregistres d'ajouter des recettes a leurs favoris (cookies)

=item Proteger l'acces a create_db.php (htpasswd)

=item Faire fonctionner les scripts AJAX sous IE

=item Enregistrer les MDP avec sha1(MDP + constante)

=item Mettre en place un utilisateur admin (?)

=item Changer les icones (?)

=back

=head2 Lien utiles

L<https://docs.google.com/document/d/1v_Kp8v4nXDSY1FR1ShEt-KJmGB1aNIwKFGr5SzAJYcc/edit?invite=CM3-pbAO>

Lisez bien ce qui suit (#RTFM)

=head3 Howto git

=over

=item Tuto @SDZ

L<http://www.siteduzero.com/tutoriel-3-254198-gerez-vos-codes-source-avec-git.html>

=item gitk (GUI) - official

=item SmartGIT (GUI)

L<http://www.syntevo.com/smartgit/index.html>

=back

=head2 FAQ

=over

=item c'est quoi ce format ?

L<http://search.cpan.org/~polgab/POD2-FR-0.02/FR/perlpod.pod>

=back

=head2 Contact

mailme !
